</br></br>

<h2>
    <?php echo $this->__('Ask question') ?>
</h2>

<form action="<?php echo $this->getActionOfForm()?>" method="post" >
    <p> <?php echo $this->__('Enter name') ?><em>*</em>
        <br> <input type="text" size="50" id="name" name="name"> </p>
    <p> <br><?php echo $this->__('Enter e-mail') ?><em>*</em>
        <br><input type="text" size="50" id="email" name="email"> </p>
    <p> <br><?php echo $this->__('Enter your question') ?><em>*</em>
        <br><textarea name="content" cols="40" rows="3" id="content" name="content"></textarea> </p>
    <p><br><input type="submit" value="<?php echo $this->__('Ask') ?>"></p>
</form>
